version: "3"

services:
  api:
    build:
      context: .
    container_name: api
    command: ["flask", "run", "--host=0.0.0.0", "--port=8800"]
    volumes:
      - ./application:/api/application
      - ./public:/api/public
    environment:
      - FLASK_DEBUG=true
      - FLASK_APP=app.py
    ports:
      - "8800:8800"